### ISSUE TITLE
Promise rejection error - Cannot read property 'st' of undefined

### ISSUE THREAD

**Issue by oakedcorn** [iobroker-community-adapters/ioBroker.worx#117]
Every now and then, the worx adapter is producing the following error. It is causing other adapters that further process the data to fail,

```
worx.0	2020-10-10 09:07:35.135	error	at Worx.emit (events.js:315:20)
worx.0	2020-10-10 09:07:35.135	error	at Worx.<anonymous> (/opt/iobroker/node_modules/iobroker.worx/main.js:173:18)
worx.0	2020-10-10 09:07:35.135	error	at Worx.setStates (/opt/iobroker/node_modules/iobroker.worx/main.js:251:32)
worx.0	2020-10-10 09:07:35.135	error	(5248) TypeError: Cannot read property 'st' of undefined
worx.0	2020-10-10 09:07:35.130	error	(5248) unhandled promise rejection: Cannot read property 'st' of undefined
Unhandled	2020-10-10 09:07:35.099	error	promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```
This is with version 1.2.3.

**Comment by Shadesh** [comment]
Same here. Adapter crashes and restarts. Debug Log attached.
[log.txt](https://github.com/iobroker-community-adapters/ioBroker.worx/files/5371371/log.txt)

**Comment by nicoh88** [comment]
Similarly, here too. But `main.js:122:36`.

```
worx.0 | 2020-11-14 19:55:01.807 | error | at /opt/iobroker/node_modules/iobroker.worx/main.js:122:36
worx.0 | 2020-11-14 19:55:01.807 | error | (7404) TypeError: Cannot read property 'sc' of undefined
worx.0 | 2020-11-14 19:55:01.807 | error | (7404) unhandled promise rejection: Cannot read property 'sc' of undefined
Unhandled | 2020-11-14 19:55:01.806 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```

**Comment by MeisterTR** [comment]
fixed in 1.2.4

**Comment by oakedcorn** [comment]
I'm still getting this error with version 1.2.4.
Because the last message before the error is "GET MQTT DATA from API: {"ota":"ota fail","mac":"XXXXXXXXXXXX"}" and I seem to be stuck on firmware 3.16 while 3.17 has been out for a while, I'm now upgrading to 3.17 over USB and will report back with further observations.

My debug log:
```
2020-11-17 13:10:00.108 - debug: worx.0 (3913) Worxcloud MQTT get Message for mower XXXXXXX (XXXXXXXXXXXXXXXXXXXX)
2020-11-17 13:10:00.110 - debug: worx.0 (3913) GET MQTT DATA from API: {"ota":"ota fail","mac":"XXXXXXXXXXXX"}
2020-11-17 13:10:00.115 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-11-17 13:10:00.116 - error: worx.0 (3913) unhandled promise rejection: Cannot read property 'st' of undefined
2020-11-17 13:10:00.120 - error: worx.0 (3913) TypeError: Cannot read property 'st' of undefined
at Worx.setStates (/opt/iobroker/node_modules/iobroker.worx/main.js:251:32)
at Worx. (/opt/iobroker/node_modules/iobroker.worx/main.js:173:18)
at Worx.emit (events.js:315:20)
at MqttClient. (/opt/iobroker/node_modules/iobroker.worx/lib/api.js:276:22)
at MqttClient.emit (events.js:315:20)
at MqttClient._handlePublish (/opt/iobroker/node_modules/mqtt/lib/client.js:1277:12)
at MqttClient._handlePacket (/opt/iobroker/node_modules/mqtt/lib/client.js:410:12)
at work (/opt/iobroker/node_modules/mqtt/lib/client.js:321:12)
at Writable.writable._write (/opt/iobroker/node_modules/mqtt/lib/client.js:335:5)
at doWrite (/opt/iobroker/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
at writeOrBuffer (/opt/iobroker/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
at Writable.write (/opt/iobroker/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
at TLSSocket.ondata (_stream_readable.js:717:22)
at TLSSocket.emit (events.js:315:20)
at addChunk (_stream_readable.js:295:12)
at readableAddChunk (_stream_readable.js:271:9)
at TLSSocket.Readable.push (_stream_readable.js:212:10)
at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
2020-11-17 13:10:00.123 - info: worx.0 (3913) cleaned everything up...
2020-11-17 13:10:00.130 - info: worx.0 (3913) terminating
2020-11-17 13:10:00.132 - info: worx.0 (3913) Terminated (NO_ERROR): Without reason
2020-11-17 13:10:00.660 - info: host.emonpi4 instance system.adapter.worx.0 terminated with code 0 (NO_ERROR)
2020-11-17 13:10:00.661 - info: host.emonpi4 Restart adapter system.adapter.worx.0 because enabled
2020-11-17 13:10:30.688 - info: host.emonpi4 instance system.adapter.worx.0 started with pid 4509
2020-11-17 13:10:32.397 - debug: worx.0 (4509) Redis Objects: Use Redis connection: 127.0.0.1:9001
2020-11-17 13:10:32.442 - debug: worx.0 (4509) Objects client ready ... initialize now
2020-11-17 13:10:32.448 - debug: worx.0 (4509) Objects create System PubSub Client
2020-11-17 13:10:32.450 - debug: worx.0 (4509) Objects create User PubSub Client
2020-11-17 13:10:32.452 - debug: worx.0 (4509) Objects client initialize lua scripts
2020-11-17 13:10:32.480 - debug: worx.0 (4509) Objects connected to redis: 127.0.0.1:9001
2020-11-17 13:10:32.488 - debug: worx.0 (4509) objectDB connected
2020-11-17 13:10:32.491 - debug: worx.0 (4509) Redis States: Use Redis connection: 127.0.0.1:6379
2020-11-17 13:10:32.498 - debug: worx.0 (4509) States create User PubSub Client
2020-11-17 13:10:32.501 - debug: worx.0 (4509) States create System PubSub Client
2020-11-17 13:10:32.511 - debug: worx.0 (4509) States connected to redis: 127.0.0.1:6379
2020-11-17 13:10:32.512 - debug: worx.0 (4509) statesDB connected
2020-11-17 13:10:32.752 - info: worx.0 (4509) starting. Version 1.2.4 in /opt/iobroker/node_modules/iobroker.worx, node: v12.18.0, js-controller: 3.1.4
2020-11-17 13:10:32.793 - info: worx.0 (4509) worx is selected

```

**Comment by MeisterTR** [comment]
now it should work...
